import { getAllMons } from './mon'
import { user } from './user'

export const collections = [
  {
    id: 0,
    monId: 1,
    mon: getAllMons.filter(mon => mon.id === 1)[0],
    userId: 1,
    user,
    rank: 'A',
    level: 1,
    imageSeq: 1,
    lastBattle: 0,
    hp: 56,
    addedHp: 0,
    power: 46,
    addedPower: 0,
    armor: 58,
    addedArmor: 0,
    sPower: 71,
    addedSPower: 0,
    sArmor: 82,
    addedSArmor: 0,
    dex: 37,
    addedDex: 0,
    total: 350,
    addedTotal: 0,
    height: 0.9,
    weight: 4.2
  },
  {
    id: 0,
    monId: 7,
    mon: getAllMons.filter(mon => mon.id === 7)[0],
    userId: 1,
    user,
    rank: 'C',
    level: 1,
    imageSeq: 1,
    lastBattle: 0,
    hp: 45,
    addedHp: 0,
    power: 54,
    addedPower: 0,
    armor: 48,
    addedArmor: 0,
    sPower: 44,
    addedSPower: 0,
    sArmor: 73,
    addedSArmor: 0,
    dex: 53,
    addedDex: 0,
    total: 317,
    addedTotal: 0
  },
  {
    id: 0,
    monId: 1,
    mon: getAllMons.filter(mon => mon.id === 1)[0],
    userId: 1,
    user,
    rank: 'A',
    level: 1,
    imageSeq: 1,
    lastBattle: 0,
    hp: 56,
    addedHp: 0,
    power: 46,
    addedPower: 0,
    armor: 58,
    addedArmor: 0,
    sPower: 71,
    addedSPower: 0,
    sArmor: 82,
    addedSArmor: 0,
    dex: 37,
    addedDex: 0,
    total: 350,
    addedTotal: 0
  }
]
